### ISSUE TITLE
Improve documentation in the project

### ISSUE THREAD

**Issue by jcamachor** [microsoft/lst-bench#177]
It would make sense to have (i) documentation describing how to create new workloads, and (ii) better description of tasks currently in the libraries.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/lst-bench/pull/207
- [ ] https://github.com/microsoft/lst-bench/issues/209
- [ ] https://github.com/microsoft/lst-bench/issues/208
```

**Comment by agr17** [comment]
Hi, there is a problem in [workloads.md](https://github.com/microsoft/lst-bench/blob/main/docs/workloads.md), all the links are broken.

For example, https://github.com/microsoft/lst-bench/blob/main/docs/src/main/resources/schemas/workload.json does not exist, the correct one is https://github.com/microsoft/lst-bench/blob/main/src/main/resources/schemas/workload.json.

The problem with all the links is that the **/docs** is not required.

**Comment by jcamachor** [comment]
> Hi, there is a problem in [workloads.md](https://github.com/microsoft/lst-bench/blob/main/docs/workloads.md), all the links are broken.
> 
> For example, https://github.com/microsoft/lst-bench/blob/main/docs/src/main/resources/schemas/workload.json does not exist, the correct one is https://github.com/microsoft/lst-bench/blob/main/src/main/resources/schemas/workload.json.
> 
> The problem with all the links is that the **/docs** is not required.

Thanks for reporting this @agr17 , good catch. I have fixed it in #211.
