### ISSUE TITLE
Integrate Cloud Analytics Benchmark (CAB) with LST-Bench

### ISSUE THREAD

**Issue by jcamachor** [microsoft/lst-bench#335]
CAB implementation: https://github.com/alexandervanrenen/cab
CAB paper: https://www.vldb.org/pvldb/vol16/p1413-renen.pdf
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/lst-bench/pull/333
- [ ] https://github.com/microsoft/lst-bench/pull/337
- [ ] https://github.com/microsoft/lst-bench/pull/338
- [ ] https://github.com/microsoft/lst-bench/pull/339
- [ ] https://github.com/microsoft/lst-bench/pull/340
```
